# Generated by Django 5.0.7 on 2024-07-26 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", "male"), ("f", "female")], max_length=1
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("aya", "Ayeyarwady"),
                            ("bgo", "Bago"),
                            ("chn", "Chin"),
                            ("kcn", "Kachin"),
                            ("kyh", "Kayah"),
                            ("kyn", "Kayin"),
                            ("mgy", "Magway"),
                            ("mdy", "Mandalay"),
                            ("mon", "Mon"),
                            ("rke", "Rakhine"),
                            ("sgg", "Sagaing"),
                            ("shn", "Shan"),
                            ("tny", "Tanintharyi"),
                            ("ygn", "Yangon"),
                        ],
                        max_length=3,
                    ),
                ),
                ("address", models.CharField(max_length=1000)),
                ("skills", models.TextField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edu_type", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=100)),
                ("grad_year", models.DateField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.employee"
                    ),
                ),
            ],
            options={
                "ordering": ["description"],
            },
        ),
    ]
