# Generated by Django 5.0.7 on 2024-07-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_employee_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="grad_year",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
