# Generated by Django 5.0.7 on 2024-07-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_education_grad_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
