# Generated by Django 5.0.7 on 2024-07-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_education_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="skills",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
